package schedule

import "testing"
import "os"
import "time"

func Test_draft(t *testing.T) {
	task, err := NewAutoGenerateDraft("./draft", "", "")
	if err != nil {
		t.Fatalf("%v", err)
	}
	defer cleanTestTrail(task, t)

	task.Start()
}
func Test_draftRename(t *testing.T) {
	task, err := NewAutoGenerateDraft("./draft", "", "")
	if err != nil {
		t.Fatalf("%v", err)
	}
	defer cleanTestTrail(task, t)

	task.Start()
	task.Start()
	task.Start()
}

func cleanTestTrail(task *AutoGenerateDraft, t *testing.T) {
	t.Logf("will clean test trail after 3 seconds ...\n")
	time.Sleep(3 * time.Second)
	_, err := os.Stat(task.Path)
	if err == nil {
		os.RemoveAll(task.Path)
	} else {
		t.Fatalf("clean test trail error: %v", err)
	}
}
