package schedule

import (
	"io/ioutil"
	"log"
	"os"
	"time"
)

// AutoGenerateDraft is a implenment of Task to generate draft
type AutoGenerateDraft struct {
	Path        string
	Suffix      string
	DefaultName string
}

func NewAutoGenerateDraft(path, suffix, defaultName string) (*AutoGenerateDraft, error) {
	_, err := ioutil.ReadDir(path)
	if err != nil {
		log.Println("create the dir: " + path)
		err = os.Mkdir(path, 0777)
	}
	if suffix == "" {
		suffix = ".txt"
	}
	if defaultName == "" {
		defaultName = "current"
	}
	g := AutoGenerateDraft{Path: path, Suffix: suffix, DefaultName: defaultName}
	return &g, nil
}

func (g *AutoGenerateDraft) Start() {
	err := g.createCurrentDraft()
	if err != nil {
		log.Printf("generate draft error: %v\n", err)
		return
	}
}

func (g *AutoGenerateDraft) createCurrentDraft() error {
	currentPath := g.Path + "/" + g.DefaultName
	_, err := os.Stat(currentPath + g.Suffix)
	if err == nil {
		now := time.Now().Format("2006-01-02")
		err = renameFile(currentPath, g.Path+"/"+now, g.Suffix)
		if err != nil {
			return err
		}
	}
	log.Println("create " + g.DefaultName + g.Suffix)
	file, err := os.Create(currentPath + g.Suffix)
	if err != nil {
		return err
	}
	defer file.Close()
	return nil
}

func renameFile(oldPath, newPath, suffix string) error {
	_, err := os.Stat(newPath + suffix)
	if err == nil {
		err = renameFile(newPath, newPath+"_1", suffix)
		if err != nil {
			return err
		}
	}
	err = os.Rename(oldPath+suffix, newPath+suffix)
	if err != nil {
		return err
	}
	log.Println("rename " + oldPath + suffix + " to " + newPath + suffix)
	return nil
}
