package main

import (
	"fmt"
	"io/ioutil"
	"os"
	"testing"
)

func Test_AutoGenerateDraft(t *testing.T) {
	path := "./draft"
	_, err := ioutil.ReadDir(path)
	if err != nil {
		fmt.Println("create the dir: " + path)
		err = os.Mkdir(path, 0777)
	}
	for index := 0; index < 10; index++ {
		err = createCurrentDraft(path)
		if err != nil {
			fmt.Println(err)
			return
		}
	}
}
