package main

import (
	"flag"
	"log"

	"github.com/wangxianzhuo/auto-draft/go-version/schedule"
)

func main() {
	path := flag.String("path", "./draft", "draft path default current")
	updateTime := flag.String("time", "00:00:00", "update draft time")
	flag.Parse()

	task, err := schedule.NewAutoGenerateDraft(*path, "", "")
	if err != nil {
		log.Fatalf("%v", err)
	}
	schedule, err := schedule.NewSchedule(*updateTime, task)
	if err != nil {
		log.Fatalf("%v", err)
	}
	schedule.Run()
}
